import {
    createContext,
    useContext,
    useEffect,
    useMemo,
    useState,
  } from "react";
  import type { ReactNode } from "react";
  
  export type ThemeMode = "light" | "dark";
  export type LanguageCode = "en" | "vi" | "zh" | "ms";
  export type TextSize = "small" | "medium" | "large";
  
  type TranslationDictionary = Record<string, string>;
  
  const translations: Record<LanguageCode, TranslationDictionary> = {
    en: {
      dashboard: "Dashboard",
      invoices: "Invoices",
      retailers: "Retailers",
      products: "Products",
      rewards: "Rewards",
      resources: "Resources",
      settings: "Settings",
      logout: "Logout",
  
      lightMode: "Light",
      darkMode: "Dark",
      language: "Language",
      textSize: "Text Size",
      textSmall: "Small",
      textMedium: "Medium",
      textLarge: "Large",
  
      adminDashboard: "Admin Dashboard",
      dashboardSubtitle:
        "Overview of invoices, retailer performance, sales, and reward activity.",
      exportCsv: "Export CSV",
      printSavePdf: "Print / Save PDF",
      pendingInvoices: "Pending Invoices",
      totalInvoices: "Total Invoices",
      totalRetailers: "Total Retailers",
      rewardRequests: "Reward Requests",
      needReview: "Need review",
      allSubmissions: "All submissions",
      registeredRetailers: "Registered retailers",
      pendingOrActive: "Pending or active",
      recentInvoices: "Recent Invoices",
      topRetailers: "Top Retailers",
      signedInAs: "Signed in as",
  
      sharedAdminSettings: "Shared Admin Settings",
      settingsSubtitle:
        "Manage admin profile information, display preferences, and logout actions for the BM Admin Dashboard.",
      adminProfile: "Admin Profile",
      adminProfileDescription:
        "This dashboard currently uses a shared admin account for BM managers.",
      adminDisplayName: "Admin Display Name",
      adminEmail: "Admin Email",
      profileNoteTitle: "Note",
      profileNoteText:
        "Since BM requested one shared admin login, this page does not create separate admin accounts yet. Individual manager preferences can be added later if BM wants separate admin users.",
  
      languagePreference: "Language Preference",
      languagePreferenceDescription:
        "Choose the preferred dashboard language for the admin view.",
      themePreference: "Theme Preference",
      themePreferenceDescription:
        "Switch between light mode and dark mode for the dashboard.",
      textSizeDescription:
        "Adjust dashboard text size for readability and accessibility.",
      preview: "Preview",
      previewText:
        "This is how dashboard text may look with the selected text size.",
  
      preferenceMemory: "Preference Memory",
      preferenceMemoryDescription:
        "Display preferences are saved locally in this browser.",
      rememberDisplayPreferences: "Remember display preferences",
      rememberDisplayPreferencesDescription:
        "Theme, language, and text size are saved automatically for this browser.",
      saveSettings: "Save Settings",
      settingsSaved: "Settings saved locally for this browser.",
  
      accessSecurity: "Access & Security",
      accessSecurityDescription: "Manage logout for the admin session.",
      sharedAccountReminderTitle: "Shared account reminder",
      sharedAccountReminderText:
        "Multiple managers may use the same admin login, so avoid changing settings during an active review session unless the team agrees.",
      logoutConfirmTitle: "Log out of admin dashboard?",
      logoutConfirmText:
        "This will return you to the login page. Any unsaved local edits may be lost.",
      cancel: "Cancel",
      invoiceReview: "Invoice Review",
        backToDashboard: "Back to Dashboard",
        invoiceReviewSubtitle:
        "Review submitted invoice details, attached proof, item totals, and approval status.",
        invoiceInformation: "Invoice Information",
        invoiceId: "Invoice ID",
        invoiceNumber: "Invoice Number",
        retailerId: "Retailer ID",
        retailerPhone: "Retailer Phone",
        submitted: "Submitted",
        totalAmount: "Total Amount",
        totalPoints: "Total Points",
        assignedTce: "Assigned TCE",
        reviewWorkflow: "Review Workflow",
        approvalStatus: "Approval Status",
        tceReview: "TCE Review",
        adminReview: "Admin Review",
        reviewedBy: "Reviewed by",
        reviewedAt: "Reviewed at",
        uploadedProof: "Uploaded Proof",
        invoiceImagePdf: "Invoice Image / PDF",
        lineItems: "Line Items",
        invoiceItems: "Invoice Items",
        product: "Product",
        quantity: "Quantity",
        price: "Price",
        subtotal: "Subtotal",
        points: "Points",
        approveInvoice: "Approve Invoice",
        reject: "Reject",
        adminRejectionReason: "Admin Rejection Reason",
        rejectionReasonPlaceholder: "Required only if rejecting this invoice.",
        readyForAdminReview: "Ready for admin review.",
        waitingForTceApproval: "Waiting for TCE approval before admin review.",
        adminApprovedMessage: "Admin review is complete. This invoice has been approved.",
        adminRejectedMessage: "Admin review is complete. This invoice has been rejected.",
        pointsApproved: "points approved",
        invoiceDenied: "Invoice denied",
        noInvoiceFile: "No uploaded invoice image or PDF available.",
        openPdf: "Open PDF in new tab",
        openImage: "Open image in new tab",
        loadingInvoice: "Loading invoice from Postgres...",
        unableToLoadInvoice: "Unable to load invoice.",
        invoiceNotFound: "Invoice not found.",
        enterRejectionReason: "Please enter a rejection reason before rejecting.",
        invoiceApprovedByAdmin: "Invoice approved by admin.",
        invoiceRejectedByAdmin: "Invoice rejected by admin.",
        unableToSubmitReview: "Unable to submit admin review.",

        invoiceRevenue: "Invoice Revenue",
        invoiceSalesOverTime: "Invoice Sales Over Time",
        invoiceSalesSubtitle:
        "Estimated sales calculated from submitted invoice line items.",
        noInvoiceSalesData: "No invoice sales data available yet.",
        oneWeek: "1 Week",
        oneMonth: "1 Month",
        oneYear: "1 Year", 
        invoicePageSubtitle:
  "Review invoice submissions after TCE review, admin approval status, and calculated reward points.",
refreshData: "Refresh Data",
pending: "Pending",
approved: "Approved",
rejected: "Rejected",
completedApprovals: "Completed approvals",
denied: "Denied",
totalInvoiceSubmissions: "Total invoice submissions",
invoiceSubmissions: "Invoice Submissions",
showing: "Showing",
invoice: "invoice",
searchInvoices: "Search invoices...",
allStatuses: "All Statuses",
loadingInvoices: "Loading invoices from Postgres...",
noInvoicesFound: "No invoices found.",
retailer: "Retailer",
region: "Region",
tce: "TCE",
admin: "Admin",
pointsEarned: "Points Earned",
totalSales: "Total Sales",
item: "item",
items: "items",
previous: "Previous",
next: "Next",
page: "Page",
of: "of",
unableToLoadInvoices: "Unable to load invoices.",
productsSubtitle:
  "Manage product catalog information, product images, point factors, and descriptions synced with Postgres.",
addProduct: "Add Product",
exportExcel: "Export Excel",
totalProducts: "Total Products",
activeProducts: "Active Products",
hiddenProducts: "Hidden Products",
seasonal: "Seasonal",
searchProducts: "Search product name, brand, formula, category...",
allBrands: "All Brands",
allCategories: "All Categories",
defaultSort: "Default Sort",
sortByCompany: "Sort by Company",
sortByPointFactor: "Sort by Point Factor",
sortBySeasonal: "Sort by Seasonal",
showHidden: "Show hidden",
loadingProducts: "Loading products from Postgres...",
noProductsFound: "No products found.",
hidden: "Hidden",
details: "Details",
edit: "Edit",
hide: "Hide",
unhide: "Unhide",
remove: "Remove",
pointFactor: "Point Factor",
productDetails: "Product Details",
unitsSold: "Units Sold",
appearedIn: "Appeared In",
pointsIssued: "Points Issued",
optionalPrice: "Optional Price",
monthlyUnitsSubmitted: "Monthly Units Submitted",
noInvoiceUnitsRecorded:
  "No invoice units recorded for this product yet.",
invoicesLabel: "invoices",
optional: "optional",
productName: "Product Name",
brand: "Brand",
formula: "Formula",
weight: "Weight",
category: "Category",
subcategory: "Subcategory",
productImageUrl: "Product Image URL",
brandImageUrl: "Brand Image URL",
shortDescription: "Short Description",
fullDescription: "Full Description",
nutrients: "Nutrients",
keyFeatures: "Key Features",
application: "Application",
saveProduct: "Save Product",
removeProductTitle: "Remove product?",
removeProductWarning:
  "This will permanently remove this product from the database. This action cannot be recovered. You will need to create a new product card to add this product back.",
removePermanently: "Remove Permanently",
removing: "Removing...",
noFormulaListed: "No formula listed",
entecShortDesc:
  "The stabilized mineral fertilizer for optimal nitrogen efficiency",
nitrophoskaShortDesc:
  "The all-in-one granule sufficient solution for durian",
fertiganicShortDesc:
  "Advanced organic nutrition enriched with natural minerals and biostimulation.",
rewardsSubtitle:
  "Manage reward items, points required, minimum tier, visibility, pinned status, seasonal status, and stock.",
addReward: "Add Reward",
retailerPreview: "Retailer Preview",
adminView: "Admin View",
totalRewards: "Total Rewards",
visibleRewards: "Visible Rewards",
hiddenRewards: "Hidden Rewards",
pinnedRewards: "Pinned Rewards",
seasonalRewards: "Seasonal Rewards",
searchRewards: "Search reward name, ID, or description...",
allTiers: "All Tiers",
sortDefaultPinned: "Default: Pinned First",
sortByName: "Sort by Name",
sortByPoints: "Sort by Points",
sortByStock: "Sort by Stock",
pointsRequired: "Points Required",
minimumTier: "Minimum Tier",
stockQuantity: "Stock Quantity",
visibleToRetailers: "Visible to retailers",
pinned: "Pinned",
unpinned: "Unpinned",
pin: "Pin",
unpin: "Unpin",
visible: "Visible",
show: "Show",
editReward: "Edit Reward",
saveReward: "Save Reward",
rewardDetails: "Reward Details",
rewardActivityLog: "Reward Activity Log",
recentRewardRedemptions: "Recent Reward Redemptions",
pointsDeducted: "Points Deducted",
quantityRedeemed: "Quantity Redeemed",
uniqueRetailers: "Unique Retailers",
redemptionStatus: "Redemption Status",
rewardCreated: "Reward created",
rewardUpdated: "Reward updated",
schedulePinning: "Schedule Pinning",
schedulePin: "Schedule Pin",
scheduleUnpin: "Schedule Unpin",
scheduledAt: "Scheduled At",
adminNotes: "Admin Notes",
addInternalComment: "Add internal comment",
saveComment: "Save Comment",
uploadRewardImage: "Upload Reward Image",
removeReward: "Remove Reward",
removeRewardWarning:
  "This will permanently remove this reward from the database. If it already has redemption history, hide it instead.",
featured: "Featured",
    },
  
    vi: {
      dashboard: "Bảng điều khiển",
      invoices: "Hóa đơn",
      retailers: "Nhà bán lẻ",
      products: "Sản phẩm",
      rewards: "Phần thưởng",
      resources: "Tài nguyên",
      settings: "Cài đặt",
      logout: "Đăng xuất",
  
      lightMode: "Sáng",
      darkMode: "Tối",
      language: "Ngôn ngữ",
      textSize: "Cỡ chữ",
      textSmall: "Nhỏ",
      textMedium: "Vừa",
      textLarge: "Lớn",
  
      adminDashboard: "Bảng điều khiển quản trị",
      dashboardSubtitle:
        "Tổng quan về hóa đơn, hiệu suất nhà bán lẻ, doanh số và hoạt động phần thưởng.",
      exportCsv: "Xuất CSV",
      printSavePdf: "In / Lưu PDF",
      pendingInvoices: "Hóa đơn chờ duyệt",
      totalInvoices: "Tổng số hóa đơn",
      totalRetailers: "Tổng số nhà bán lẻ",
      rewardRequests: "Yêu cầu phần thưởng",
      needReview: "Cần xem xét",
      allSubmissions: "Tất cả bài gửi",
      registeredRetailers: "Nhà bán lẻ đã đăng ký",
      pendingOrActive: "Đang chờ hoặc đang hoạt động",
      recentInvoices: "Hóa đơn gần đây",
      topRetailers: "Nhà bán lẻ hàng đầu",
      signedInAs: "Đăng nhập với tài khoản",
  
      sharedAdminSettings: "Cài đặt quản trị chung",
      settingsSubtitle:
        "Quản lý thông tin hồ sơ quản trị, tùy chọn hiển thị và thao tác đăng xuất cho BM Admin Dashboard.",
      adminProfile: "Hồ sơ quản trị",
      adminProfileDescription:
        "Bảng điều khiển này hiện sử dụng một tài khoản quản trị chung cho các quản lý BM.",
      adminDisplayName: "Tên hiển thị quản trị",
      adminEmail: "Email quản trị",
      profileNoteTitle: "Ghi chú",
      profileNoteText:
        "Vì BM yêu cầu một tài khoản đăng nhập quản trị chung, trang này chưa tạo tài khoản riêng cho từng quản lý. Có thể thêm tùy chọn riêng cho từng quản lý sau nếu BM cần.",
  
      languagePreference: "Tùy chọn ngôn ngữ",
      languagePreferenceDescription:
        "Chọn ngôn ngữ hiển thị cho bảng điều khiển quản trị.",
      themePreference: "Tùy chọn giao diện",
      themePreferenceDescription:
        "Chuyển đổi giữa giao diện sáng và giao diện tối.",
      textSizeDescription:
        "Điều chỉnh cỡ chữ của bảng điều khiển để dễ đọc hơn.",
      preview: "Xem trước",
      previewText:
        "Đây là cách văn bản trên bảng điều khiển hiển thị với cỡ chữ đã chọn.",
  
      preferenceMemory: "Ghi nhớ tùy chọn",
      preferenceMemoryDescription:
        "Tùy chọn hiển thị được lưu cục bộ trong trình duyệt này.",
      rememberDisplayPreferences: "Ghi nhớ tùy chọn hiển thị",
      rememberDisplayPreferencesDescription:
        "Giao diện, ngôn ngữ và cỡ chữ sẽ được tự động lưu cho trình duyệt này.",
      saveSettings: "Lưu cài đặt",
      settingsSaved: "Cài đặt đã được lưu cục bộ cho trình duyệt này.",
  
      accessSecurity: "Truy cập & Bảo mật",
      accessSecurityDescription: "Quản lý đăng xuất khỏi phiên quản trị.",
      sharedAccountReminderTitle: "Nhắc nhở về tài khoản chung",
      sharedAccountReminderText:
        "Nhiều quản lý có thể dùng cùng một tài khoản quản trị, vì vậy hãy tránh thay đổi cài đặt trong lúc đang có phiên kiểm duyệt nếu nhóm chưa thống nhất.",
      logoutConfirmTitle: "Đăng xuất khỏi bảng điều khiển quản trị?",
      logoutConfirmText:
        "Bạn sẽ quay lại trang đăng nhập. Các chỉnh sửa cục bộ chưa lưu có thể bị mất.",
      cancel: "Hủy",
      invoiceReview: "Duyệt hóa đơn",
backToDashboard: "Quay lại bảng điều khiển",
invoiceReviewSubtitle:
  "Xem chi tiết hóa đơn đã gửi, chứng từ đính kèm, tổng tiền và trạng thái phê duyệt.",
invoiceInformation: "Thông tin hóa đơn",
invoiceId: "Mã hóa đơn",
invoiceNumber: "Số hóa đơn",
retailerId: "Mã nhà bán lẻ",
retailerPhone: "Số điện thoại nhà bán lẻ",
submitted: "Ngày gửi",
totalAmount: "Tổng tiền",
totalPoints: "Tổng điểm",
assignedTce: "TCE phụ trách",
reviewWorkflow: "Quy trình duyệt",
approvalStatus: "Trạng thái phê duyệt",
tceReview: "TCE duyệt",
adminReview: "Admin duyệt",
reviewedBy: "Người duyệt",
reviewedAt: "Thời gian duyệt",
uploadedProof: "Chứng từ đã tải lên",
invoiceImagePdf: "Hình ảnh / PDF hóa đơn",
lineItems: "Chi tiết sản phẩm",
invoiceItems: "Sản phẩm trong hóa đơn",
product: "Sản phẩm",
quantity: "Số lượng",
price: "Giá",
subtotal: "Tạm tính",
points: "Điểm",
approveInvoice: "Phê duyệt hóa đơn",
reject: "Từ chối",
adminRejectionReason: "Lý do từ chối của admin",
rejectionReasonPlaceholder: "Chỉ bắt buộc khi từ chối hóa đơn.",
readyForAdminReview: "Sẵn sàng để admin duyệt.",
waitingForTceApproval: "Đang chờ TCE phê duyệt trước khi admin duyệt.",
adminApprovedMessage: "Admin đã hoàn tất duyệt. Hóa đơn này đã được phê duyệt.",
adminRejectedMessage: "Admin đã hoàn tất duyệt. Hóa đơn này đã bị từ chối.",
pointsApproved: "điểm đã được phê duyệt",
invoiceDenied: "Hóa đơn bị từ chối",
noInvoiceFile: "Chưa có hình ảnh hoặc PDF hóa đơn.",
openPdf: "Mở PDF trong tab mới",
openImage: "Mở hình ảnh trong tab mới",
loadingInvoice: "Đang tải hóa đơn từ Postgres...",
unableToLoadInvoice: "Không thể tải hóa đơn.",
invoiceNotFound: "Không tìm thấy hóa đơn.",
enterRejectionReason: "Vui lòng nhập lý do từ chối trước khi từ chối.",
invoiceApprovedByAdmin: "Hóa đơn đã được admin phê duyệt.",
invoiceRejectedByAdmin: "Hóa đơn đã bị admin từ chối.",
unableToSubmitReview: "Không thể gửi kết quả duyệt.",

invoiceRevenue: "Doanh thu hóa đơn",
invoiceSalesOverTime: "Doanh thu hóa đơn theo thời gian",
invoiceSalesSubtitle:
  "Doanh thu ước tính được tính từ các dòng sản phẩm trong hóa đơn đã gửi.",
noInvoiceSalesData: "Chưa có dữ liệu doanh thu hóa đơn.",
oneWeek: "1 tuần",
oneMonth: "1 tháng",
oneYear: "1 năm",
invoicePageSubtitle:
  "Xem các hóa đơn sau khi TCE đã duyệt, trạng thái phê duyệt của admin và điểm thưởng đã tính.",
refreshData: "Làm mới dữ liệu",
pending: "Đang chờ",
approved: "Đã duyệt",
rejected: "Đã từ chối",
completedApprovals: "Phê duyệt đã hoàn tất",
denied: "Bị từ chối",
totalInvoiceSubmissions: "Tổng số hóa đơn đã gửi",
invoiceSubmissions: "Danh sách hóa đơn",
showing: "Đang hiển thị",
invoice: "hóa đơn",
searchInvoices: "Tìm kiếm hóa đơn...",
allStatuses: "Tất cả trạng thái",
loadingInvoices: "Đang tải hóa đơn từ Postgres...",
noInvoicesFound: "Không tìm thấy hóa đơn.",
retailer: "Nhà bán lẻ",
region: "Khu vực",
tce: "TCE",
admin: "Admin",
pointsEarned: "Điểm nhận được",
totalSales: "Tổng doanh số",
item: "mặt hàng",
items: "mặt hàng",
previous: "Trước",
next: "Sau",
page: "Trang",
of: "trên",
unableToLoadInvoices: "Không thể tải hóa đơn.",
// products: "Sản phẩm",
productsSubtitle:
  "Quản lý danh mục sản phẩm, hình ảnh, hệ số điểm và mô tả được đồng bộ với Postgres.",
addProduct: "Thêm sản phẩm",
exportExcel: "Xuất Excel",
totalProducts: "Tổng sản phẩm",
activeProducts: "Sản phẩm đang hoạt động",
hiddenProducts: "Sản phẩm đã ẩn",
seasonal: "Theo mùa",
searchProducts: "Tìm tên sản phẩm, thương hiệu, công thức, danh mục...",
allBrands: "Tất cả thương hiệu",
allCategories: "Tất cả danh mục",
defaultSort: "Sắp xếp mặc định",
sortByCompany: "Sắp xếp theo công ty",
sortByPointFactor: "Sắp xếp theo hệ số điểm",
sortBySeasonal: "Sắp xếp theo sản phẩm theo mùa",
showHidden: "Hiển thị sản phẩm đã ẩn",
loadingProducts: "Đang tải sản phẩm từ Postgres...",
noProductsFound: "Không tìm thấy sản phẩm.",
hidden: "Đã ẩn",
details: "Chi tiết",
edit: "Chỉnh sửa",
hide: "Ẩn",
unhide: "Bỏ ẩn",
remove: "Xóa",
pointFactor: "Hệ số điểm",
productDetails: "Chi tiết sản phẩm",
unitsSold: "Số lượng đã bán",
appearedIn: "Xuất hiện trong",
pointsIssued: "Điểm đã phát hành",
optionalPrice: "Giá tùy chọn",
monthlyUnitsSubmitted: "Số lượng được gửi theo tháng",
noInvoiceUnitsRecorded:
  "Chưa có số lượng hóa đơn nào được ghi nhận cho sản phẩm này.",
invoicesLabel: "hóa đơn",
optional: "tùy chọn",
productName: "Tên sản phẩm",
brand: "Thương hiệu",
formula: "Công thức",
weight: "Khối lượng",
category: "Danh mục",
subcategory: "Danh mục phụ",
productImageUrl: "URL hình ảnh sản phẩm",
brandImageUrl: "URL hình ảnh thương hiệu",
shortDescription: "Mô tả ngắn",
fullDescription: "Mô tả đầy đủ",
nutrients: "Dinh dưỡng",
keyFeatures: "Tính năng chính",
application: "Cách sử dụng",
saveProduct: "Lưu sản phẩm",
// cancel: "Hủy",
entecShortDesc:
    "Phân khoáng ổn định giúp tối ưu hiệu quả sử dụng đạm.",
  nitrophoskaShortDesc:
    "Giải pháp phân bón dạng hạt toàn diện, đáp ứng nhu cầu cho cây sầu riêng.",
  fertiganicShortDesc:
    "Dinh dưỡng hữu cơ tiên tiến, được bổ sung khoáng chất tự nhiên và chất kích thích sinh học.",
rewardsSubtitle:
  "Quản lý phần thưởng, điểm yêu cầu, cấp tối thiểu, khả năng hiển thị, trạng thái ghim, trạng thái theo mùa và tồn kho.",
addReward: "Thêm phần thưởng",
retailerPreview: "Xem trước cho nhà bán lẻ",
adminView: "Chế độ admin",
totalRewards: "Tổng phần thưởng",
visibleRewards: "Phần thưởng hiển thị",
hiddenRewards: "Phần thưởng đã ẩn",
pinnedRewards: "Phần thưởng được ghim",
seasonalRewards: "Phần thưởng theo mùa",
searchRewards: "Tìm tên phần thưởng, ID hoặc mô tả...",
allTiers: "Tất cả cấp",
sortDefaultPinned: "Mặc định: ưu tiên phần thưởng ghim",
sortByName: "Sắp xếp theo tên",
sortByPoints: "Sắp xếp theo điểm",
sortByStock: "Sắp xếp theo tồn kho",
pointsRequired: "Điểm yêu cầu",
minimumTier: "Cấp tối thiểu",
stockQuantity: "Số lượng tồn kho",
visibleToRetailers: "Hiển thị cho nhà bán lẻ",
pinned: "Đã ghim",
unpinned: "Chưa ghim",
pin: "Ghim",
unpin: "Bỏ ghim",

visible: "Hiển thị",
show: "Hiển thị",
editReward: "Chỉnh sửa phần thưởng",
saveReward: "Lưu phần thưởng",
rewardDetails: "Chi tiết phần thưởng",
rewardActivityLog: "Nhật ký hoạt động phần thưởng",
recentRewardRedemptions: "Lịch sử đổi thưởng gần đây",
pointsDeducted: "Điểm đã trừ",
quantityRedeemed: "Số lượng đã đổi",
uniqueRetailers: "Nhà bán lẻ duy nhất",
redemptionStatus: "Trạng thái đổi thưởng",
rewardCreated: "Phần thưởng đã được tạo",
rewardUpdated: "Phần thưởng đã được cập nhật",
schedulePinning: "Lên lịch ghim",
schedulePin: "Lên lịch ghim",
scheduleUnpin: "Lên lịch bỏ ghim",
scheduledAt: "Thời gian đã lên lịch",
adminNotes: "Ghi chú admin",
addInternalComment: "Thêm bình luận nội bộ",
saveComment: "Lưu bình luận",
uploadRewardImage: "Tải ảnh phần thưởng",
removeReward: "Xóa phần thưởng",
removeRewardWarning:
  "Thao tác này sẽ xóa vĩnh viễn phần thưởng khỏi cơ sở dữ liệu. Nếu phần thưởng đã có lịch sử đổi thưởng, hãy ẩn thay vì xóa.",
featured: "Nổi bật",
    },
  
    zh: {
      dashboard: "仪表板",
      invoices: "发票",
      retailers: "零售商",
      products: "产品",
      rewards: "奖励",
      resources: "资源",
      settings: "设置",
      logout: "退出登录",
  
      lightMode: "浅色",
      darkMode: "深色",
      language: "语言",
      textSize: "字体大小",
      textSmall: "小",
      textMedium: "中",
      textLarge: "大",
  
      adminDashboard: "管理员仪表板",
      dashboardSubtitle: "查看发票、零售商表现、销售和奖励活动。",
      exportCsv: "导出 CSV",
      printSavePdf: "打印 / 保存 PDF",
      pendingInvoices: "待处理发票",
      totalInvoices: "发票总数",
      totalRetailers: "零售商总数",
      rewardRequests: "奖励申请",
      needReview: "需要审核",
      allSubmissions: "所有提交",
      registeredRetailers: "已注册零售商",
      pendingOrActive: "待处理或进行中",
      recentInvoices: "最近发票",
      topRetailers: "顶级零售商",
      signedInAs: "当前登录",
  
      sharedAdminSettings: "共享管理员设置",
      settingsSubtitle: "管理管理员资料、显示偏好和退出登录操作。",
      adminProfile: "管理员资料",
      adminProfileDescription: "此仪表板目前使用一个共享管理员账号。",
      adminDisplayName: "管理员显示名称",
      adminEmail: "管理员邮箱",
      profileNoteTitle: "备注",
      profileNoteText:
        "由于 BM 要求使用一个共享管理员登录账号，此页面暂时不创建单独管理员账号。如果 BM 之后需要，可以再添加个人管理员偏好设置。",
  
      languagePreference: "语言偏好",
      languagePreferenceDescription: "选择管理员仪表板的显示语言。",
      themePreference: "主题偏好",
      themePreferenceDescription: "在浅色模式和深色模式之间切换。",
      textSizeDescription: "调整仪表板字体大小，提高可读性。",
      preview: "预览",
      previewText: "这是所选字体大小下的仪表板文字效果。",
  
      preferenceMemory: "偏好记忆",
      preferenceMemoryDescription: "显示偏好会保存在当前浏览器中。",
      rememberDisplayPreferences: "记住显示偏好",
      rememberDisplayPreferencesDescription:
        "主题、语言和字体大小会自动保存到当前浏览器。",
      saveSettings: "保存设置",
      settingsSaved: "设置已保存到当前浏览器。",
  
      accessSecurity: "访问与安全",
      accessSecurityDescription: "管理管理员会话的退出登录。",
      sharedAccountReminderTitle: "共享账号提醒",
      sharedAccountReminderText:
        "多个管理人员可能使用同一个管理员账号，因此在团队未确认前，请避免在审核过程中更改设置。",
      logoutConfirmTitle: "退出管理员仪表板？",
      logoutConfirmText: "这会返回登录页面。未保存的本地更改可能会丢失。",
      cancel: "取消",
      invoiceReview: "Invoice Review",
backToDashboard: "Back to Dashboard",
invoiceReviewSubtitle:
  "Review submitted invoice details, attached proof, item totals, and approval status.",
invoiceInformation: "Invoice Information",
invoiceId: "Invoice ID",
invoiceNumber: "Invoice Number",
retailerId: "Retailer ID",
retailerPhone: "Retailer Phone",
submitted: "Submitted",
totalAmount: "Total Amount",
totalPoints: "Total Points",
assignedTce: "Assigned TCE",
reviewWorkflow: "Review Workflow",
approvalStatus: "Approval Status",
tceReview: "TCE Review",
adminReview: "Admin Review",
reviewedBy: "Reviewed by",
reviewedAt: "Reviewed at",
uploadedProof: "Uploaded Proof",
invoiceImagePdf: "Invoice Image / PDF",
lineItems: "Line Items",
invoiceItems: "Invoice Items",
product: "Product",
quantity: "Quantity",
price: "Price",
subtotal: "Subtotal",
points: "Points",
approveInvoice: "Approve Invoice",
reject: "Reject",
adminRejectionReason: "Admin Rejection Reason",
rejectionReasonPlaceholder: "Required only if rejecting this invoice.",
readyForAdminReview: "Ready for admin review.",
waitingForTceApproval: "Waiting for TCE approval before admin review.",
adminApprovedMessage: "Admin review is complete. This invoice has been approved.",
adminRejectedMessage: "Admin review is complete. This invoice has been rejected.",
pointsApproved: "points approved",
invoiceDenied: "Invoice denied",
noInvoiceFile: "No uploaded invoice image or PDF available.",
openPdf: "Open PDF in new tab",
openImage: "Open image in new tab",
loadingInvoice: "Loading invoice from Postgres...",
unableToLoadInvoice: "Unable to load invoice.",
invoiceNotFound: "Invoice not found.",
enterRejectionReason: "Please enter a rejection reason before rejecting.",
invoiceApprovedByAdmin: "Invoice approved by admin.",
invoiceRejectedByAdmin: "Invoice rejected by admin.",
unableToSubmitReview: "Unable to submit admin review.",

invoiceRevenue: "Invoice Revenue",
invoiceSalesOverTime: "Invoice Sales Over Time",
invoiceSalesSubtitle:
  "Estimated sales calculated from submitted invoice line items.",
noInvoiceSalesData: "No invoice sales data available yet.",
oneWeek: "1 Week",
oneMonth: "1 Month",
oneYear: "1 Year",
invoicePageSubtitle:
  "查看已完成 TCE 审核后的发票提交、管理员审批状态和计算出的奖励积分。",
refreshData: "刷新数据",
pending: "待处理",
approved: "已批准",
rejected: "已拒绝",
completedApprovals: "审批已完成",
denied: "已拒绝",
totalInvoiceSubmissions: "提交发票总数",
invoiceSubmissions: "发票提交记录",
showing: "正在显示",
invoice: "发票",
searchInvoices: "搜索发票...",
allStatuses: "所有状态",
loadingInvoices: "正在从 Postgres 加载发票...",
noInvoicesFound: "未找到发票。",
retailer: "零售商",
region: "区域",
tce: "TCE",
admin: "管理员",
pointsEarned: "获得积分",
totalSales: "总销售额",
item: "项目",
items: "项目",
previous: "上一页",
next: "下一页",
page: "第",
of: "页，共",
unableToLoadInvoices: "无法加载发票。",
// products: "产品",
productsSubtitle:
  "管理与 Postgres 同步的产品目录、产品图片、积分系数和描述。",
addProduct: "添加产品",
exportExcel: "导出 Excel",
totalProducts: "产品总数",
activeProducts: "启用产品",
hiddenProducts: "隐藏产品",
seasonal: "季节性",
searchProducts: "搜索产品名称、品牌、配方、类别...",
allBrands: "所有品牌",
allCategories: "所有类别",
defaultSort: "默认排序",
sortByCompany: "按公司排序",
sortByPointFactor: "按积分系数排序",
sortBySeasonal: "按季节性排序",
showHidden: "显示隐藏产品",
loadingProducts: "正在从 Postgres 加载产品...",
noProductsFound: "未找到产品。",
hidden: "已隐藏",
details: "详情",
edit: "编辑",
hide: "隐藏",
unhide: "取消隐藏",
remove: "删除",
pointFactor: "积分系数",
productDetails: "产品详情",
unitsSold: "售出数量",
appearedIn: "出现于",
pointsIssued: "已发放积分",
optionalPrice: "可选价格",
monthlyUnitsSubmitted: "每月提交数量",
noInvoiceUnitsRecorded:
  "该产品尚无发票数量记录。",
invoicesLabel: "张发票",
optional: "可选",
productName: "产品名称",
brand: "品牌",
formula: "配方",
weight: "重量",
category: "类别",
subcategory: "子类别",
productImageUrl: "产品图片 URL",
brandImageUrl: "品牌图片 URL",
shortDescription: "简短描述",
fullDescription: "完整描述",
nutrients: "营养成分",
keyFeatures: "主要特点",
application: "使用方法",
saveProduct: "保存产品",
// cancel: "取消",
entecShortDesc:
    "稳定型矿物肥料，可优化氮素利用效率。",
  nitrophoskaShortDesc:
    "满足榴莲需求的一体化颗粒肥解决方案。",
  fertiganicShortDesc:
    "富含天然矿物质和生物刺激成分的先进有机营养方案。",
rewardsSubtitle:
  "管理奖励项目、所需积分、最低等级、可见性、置顶状态、季节性状态和库存。",
addReward: "添加奖励",
retailerPreview: "零售商预览",
adminView: "管理员视图",
totalRewards: "奖励总数",
visibleRewards: "可见奖励",
hiddenRewards: "隐藏奖励",
pinnedRewards: "置顶奖励",
seasonalRewards: "季节性奖励",
searchRewards: "搜索奖励名称、ID 或描述...",
allTiers: "所有等级",
sortDefaultPinned: "默认：置顶优先",
sortByName: "按名称排序",
sortByPoints: "按积分排序",
sortByStock: "按库存排序",
pointsRequired: "所需积分",
minimumTier: "最低等级",
stockQuantity: "库存数量",
visibleToRetailers: "对零售商可见",
pinned: "已置顶",
unpinned: "未置顶",
pin: "置顶",
unpin: "取消置顶",
visible: "可见",
show: "显示",
editReward: "编辑奖励",
saveReward: "保存奖励",
rewardDetails: "奖励详情",
rewardActivityLog: "奖励活动记录",
recentRewardRedemptions: "最近兑换记录",
pointsDeducted: "扣除积分",
quantityRedeemed: "兑换数量",
uniqueRetailers: "独立零售商",
redemptionStatus: "兑换状态",
rewardCreated: "奖励已创建",
rewardUpdated: "奖励已更新",
schedulePinning: "设置置顶计划",
schedulePin: "计划置顶",
scheduleUnpin: "计划取消置顶",
scheduledAt: "计划时间",
adminNotes: "管理员备注",
addInternalComment: "添加内部评论",
saveComment: "保存评论",
uploadRewardImage: "上传奖励图片",
removeReward: "删除奖励",
removeRewardWarning:
  "这将从数据库中永久删除该奖励。如果该奖励已有兑换记录，请改为隐藏它。",
featured: "推荐",
    },
  
    ms: {
      dashboard: "Papan Pemuka",
      invoices: "Invois",
      retailers: "Peruncit",
      products: "Produk",
      rewards: "Ganjaran",
      resources: "Sumber",
      settings: "Tetapan",
      logout: "Log Keluar",
  
      lightMode: "Cerah",
      darkMode: "Gelap",
      language: "Bahasa",
      textSize: "Saiz Teks",
      textSmall: "Kecil",
      textMedium: "Sederhana",
      textLarge: "Besar",
  
      adminDashboard: "Papan Pemuka Admin",
      dashboardSubtitle:
        "Gambaran keseluruhan invois, prestasi peruncit, jualan dan aktiviti ganjaran.",
      exportCsv: "Eksport CSV",
      printSavePdf: "Cetak / Simpan PDF",
      pendingInvoices: "Invois Tertunda",
      totalInvoices: "Jumlah Invois",
      totalRetailers: "Jumlah Peruncit",
      rewardRequests: "Permintaan Ganjaran",
      needReview: "Perlu disemak",
      allSubmissions: "Semua penghantaran",
      registeredRetailers: "Peruncit berdaftar",
      pendingOrActive: "Tertunda atau aktif",
      recentInvoices: "Invois Terkini",
      topRetailers: "Peruncit Teratas",
      signedInAs: "Log masuk sebagai",
  
      sharedAdminSettings: "Tetapan Admin Bersama",
      settingsSubtitle:
        "Urus maklumat profil admin, pilihan paparan dan tindakan log keluar untuk papan pemuka BM.",
      adminProfile: "Profil Admin",
      adminProfileDescription:
        "Papan pemuka ini menggunakan satu akaun admin bersama untuk pengurus BM.",
      adminDisplayName: "Nama Paparan Admin",
      adminEmail: "E-mel Admin",
      profileNoteTitle: "Nota",
      profileNoteText:
        "Oleh kerana BM meminta satu log masuk admin bersama, halaman ini belum mencipta akaun admin berasingan. Pilihan individu boleh ditambah kemudian jika BM memerlukannya.",
  
      languagePreference: "Pilihan Bahasa",
      languagePreferenceDescription:
        "Pilih bahasa paparan untuk papan pemuka admin.",
      themePreference: "Pilihan Tema",
      themePreferenceDescription:
        "Tukar antara mod cerah dan mod gelap untuk papan pemuka.",
      textSizeDescription:
        "Laraskan saiz teks papan pemuka untuk kebolehbacaan.",
      preview: "Pratonton",
      previewText:
        "Beginilah rupa teks papan pemuka dengan saiz teks yang dipilih.",
  
      preferenceMemory: "Ingatan Pilihan",
      preferenceMemoryDescription:
        "Pilihan paparan disimpan secara tempatan dalam pelayar ini.",
      rememberDisplayPreferences: "Ingat pilihan paparan",
      rememberDisplayPreferencesDescription:
        "Tema, bahasa dan saiz teks disimpan secara automatik untuk pelayar ini.",
      saveSettings: "Simpan Tetapan",
      settingsSaved: "Tetapan disimpan secara tempatan untuk pelayar ini.",
  
      accessSecurity: "Akses & Keselamatan",
      accessSecurityDescription: "Urus log keluar untuk sesi admin.",
      sharedAccountReminderTitle: "Peringatan akaun bersama",
      sharedAccountReminderText:
        "Beberapa pengurus mungkin menggunakan log masuk admin yang sama, jadi elakkan menukar tetapan semasa sesi semakan aktif kecuali pasukan bersetuju.",
      logoutConfirmTitle: "Log keluar daripada papan pemuka admin?",
      logoutConfirmText:
        "Anda akan kembali ke halaman log masuk. Sebarang suntingan tempatan yang belum disimpan mungkin hilang.",
      cancel: "Batal",
      invoiceReview: "Invoice Review",
backToDashboard: "Back to Dashboard",
invoiceReviewSubtitle:
  "Review submitted invoice details, attached proof, item totals, and approval status.",
invoiceInformation: "Invoice Information",
invoiceId: "Invoice ID",
invoiceNumber: "Invoice Number",
retailerId: "Retailer ID",
retailerPhone: "Retailer Phone",
submitted: "Submitted",
totalAmount: "Total Amount",
totalPoints: "Total Points",
assignedTce: "Assigned TCE",
reviewWorkflow: "Review Workflow",
approvalStatus: "Approval Status",
tceReview: "TCE Review",
adminReview: "Admin Review",
reviewedBy: "Reviewed by",
reviewedAt: "Reviewed at",
uploadedProof: "Uploaded Proof",
invoiceImagePdf: "Invoice Image / PDF",
lineItems: "Line Items",
invoiceItems: "Invoice Items",
product: "Product",
quantity: "Quantity",
price: "Price",
subtotal: "Subtotal",
points: "Points",
approveInvoice: "Approve Invoice",
reject: "Reject",
adminRejectionReason: "Admin Rejection Reason",
rejectionReasonPlaceholder: "Required only if rejecting this invoice.",
readyForAdminReview: "Ready for admin review.",
waitingForTceApproval: "Waiting for TCE approval before admin review.",
adminApprovedMessage: "Admin review is complete. This invoice has been approved.",
adminRejectedMessage: "Admin review is complete. This invoice has been rejected.",
pointsApproved: "points approved",
invoiceDenied: "Invoice denied",
noInvoiceFile: "No uploaded invoice image or PDF available.",
openPdf: "Open PDF in new tab",
openImage: "Open image in new tab",
loadingInvoice: "Loading invoice from Postgres...",
unableToLoadInvoice: "Unable to load invoice.",
invoiceNotFound: "Invoice not found.",
enterRejectionReason: "Please enter a rejection reason before rejecting.",
invoiceApprovedByAdmin: "Invoice approved by admin.",
invoiceRejectedByAdmin: "Invoice rejected by admin.",
unableToSubmitReview: "Unable to submit admin review.",

invoiceRevenue: "Invoice Revenue",
invoiceSalesOverTime: "Invoice Sales Over Time",
invoiceSalesSubtitle:
  "Estimated sales calculated from submitted invoice line items.",
noInvoiceSalesData: "No invoice sales data available yet.",
oneWeek: "1 Week",
oneMonth: "1 Month",
oneYear: "1 Year",
invoicePageSubtitle:
  "Semak penyerahan invois selepas semakan TCE, status kelulusan admin, dan mata ganjaran yang dikira.",
refreshData: "Muat Semula Data",
pending: "Menunggu",
approved: "Diluluskan",
rejected: "Ditolak",
completedApprovals: "Kelulusan selesai",
denied: "Ditolak",
totalInvoiceSubmissions: "Jumlah penyerahan invois",
invoiceSubmissions: "Penyerahan Invois",
showing: "Memaparkan",
invoice: "invois",
searchInvoices: "Cari invois...",
allStatuses: "Semua Status",
loadingInvoices: "Memuatkan invois daripada Postgres...",
noInvoicesFound: "Tiada invois dijumpai.",
retailer: "Peruncit",
region: "Wilayah",
tce: "TCE",
admin: "Admin",
pointsEarned: "Mata Diperoleh",
totalSales: "Jumlah Jualan",
item: "item",
items: "item",
previous: "Sebelumnya",
next: "Seterusnya",
page: "Halaman",
of: "daripada",
unableToLoadInvoices: "Tidak dapat memuatkan invois.",
// products: "Produk",
productsSubtitle:
  "Urus maklumat katalog produk, imej produk, faktor mata, dan penerangan yang diselaraskan dengan Postgres.",
addProduct: "Tambah Produk",
exportExcel: "Eksport Excel",
totalProducts: "Jumlah Produk",
activeProducts: "Produk Aktif",
hiddenProducts: "Produk Tersembunyi",
seasonal: "Bermusim",
searchProducts: "Cari nama produk, jenama, formula, kategori...",
allBrands: "Semua Jenama",
allCategories: "Semua Kategori",
defaultSort: "Susunan Lalai",
sortByCompany: "Susun Mengikut Syarikat",
sortByPointFactor: "Susun Mengikut Faktor Mata",
sortBySeasonal: "Susun Mengikut Bermusim",
showHidden: "Tunjuk produk tersembunyi",
loadingProducts: "Memuatkan produk daripada Postgres...",
noProductsFound: "Tiada produk dijumpai.",
hidden: "Tersembunyi",
details: "Butiran",
edit: "Edit",
hide: "Sembunyikan",
unhide: "Nyahsembunyi",
remove: "Buang",
pointFactor: "Faktor Mata",
productDetails: "Butiran Produk",
unitsSold: "Unit Terjual",
appearedIn: "Muncul Dalam",
pointsIssued: "Mata Dikeluarkan",
optionalPrice: "Harga Pilihan",
monthlyUnitsSubmitted: "Unit Bulanan Dihantar",
noInvoiceUnitsRecorded:
  "Tiada unit invois direkodkan untuk produk ini lagi.",
invoicesLabel: "invois",
optional: "pilihan",
productName: "Nama Produk",
brand: "Jenama",
formula: "Formula",
weight: "Berat",
category: "Kategori",
subcategory: "Subkategori",
productImageUrl: "URL Imej Produk",
brandImageUrl: "URL Imej Jenama",
shortDescription: "Penerangan Ringkas",
fullDescription: "Penerangan Penuh",
nutrients: "Nutrien",
keyFeatures: "Ciri Utama",
application: "Penggunaan",
saveProduct: "Simpan Produk",
// cancel: "Batal",
entecShortDesc:
    "Baja mineral stabil untuk mengoptimumkan kecekapan nitrogen.",
  nitrophoskaShortDesc:
    "Penyelesaian granul serba lengkap yang mencukupi untuk durian.",
  fertiganicShortDesc:
    "Nutrisi organik lanjutan diperkaya dengan mineral semula jadi dan biostimulasi.",
rewardsSubtitle:
  "Urus item ganjaran, mata diperlukan, tahap minimum, keterlihatan, status pin, status bermusim, dan stok.",
addReward: "Tambah Ganjaran",
retailerPreview: "Pratonton Peruncit",
adminView: "Paparan Admin",
totalRewards: "Jumlah Ganjaran",
visibleRewards: "Ganjaran Kelihatan",
hiddenRewards: "Ganjaran Tersembunyi",
pinnedRewards: "Ganjaran Dipin",
seasonalRewards: "Ganjaran Bermusim",
searchRewards: "Cari nama ganjaran, ID, atau penerangan...",
allTiers: "Semua Tahap",
sortDefaultPinned: "Lalai: Dipin Dahulu",
sortByName: "Susun Mengikut Nama",
sortByPoints: "Susun Mengikut Mata",
sortByStock: "Susun Mengikut Stok",
pointsRequired: "Mata Diperlukan",
minimumTier: "Tahap Minimum",
stockQuantity: "Kuantiti Stok",
visibleToRetailers: "Kelihatan kepada peruncit",
pinned: "Dipin",
unpinned: "Tidak Dipin",
pin: "Pin",
unpin: "Nyahpin",
visible: "Kelihatan",
show: "Tunjuk",
editReward: "Edit Ganjaran",
saveReward: "Simpan Ganjaran",
rewardDetails: "Butiran Ganjaran",
rewardActivityLog: "Log Aktiviti Ganjaran",
recentRewardRedemptions: "Log Penebusan Ganjaran Terkini",
pointsDeducted: "Mata Ditolak",
quantityRedeemed: "Kuantiti Ditebus",
uniqueRetailers: "Peruncit Unik",
redemptionStatus: "Status Penebusan",
rewardCreated: "Ganjaran dicipta",
rewardUpdated: "Ganjaran dikemas kini",
schedulePinning: "Jadual Pin",
schedulePin: "Jadualkan Pin",
scheduleUnpin: "Jadualkan Nyahpin",
scheduledAt: "Masa Dijadualkan",
adminNotes: "Nota Admin",
addInternalComment: "Tambah komen dalaman",
saveComment: "Simpan Komen",
uploadRewardImage: "Muat Naik Imej Ganjaran",
removeReward: "Buang Ganjaran",
removeRewardWarning:
  "Ini akan membuang ganjaran ini secara kekal daripada pangkalan data. Jika ganjaran sudah mempunyai sejarah penebusan, sembunyikan ganjaran itu sebaliknya.",
featured: "Ditampilkan",
    },
  };
  
  type AppPreferencesContextValue = {
    theme: ThemeMode;
    language: LanguageCode;
    textSize: TextSize;
    setTheme: (theme: ThemeMode) => void;
    toggleTheme: () => void;
    setLanguage: (language: LanguageCode) => void;
    setTextSize: (textSize: TextSize) => void;
    t: (key: string) => string;
  };
  
  const AppPreferencesContext =
    createContext<AppPreferencesContextValue | null>(null);
  
  export function AppPreferencesProvider({ children }: { children: ReactNode }) {
    const [theme, setThemeState] = useState<ThemeMode>(() => {
      const savedTheme = localStorage.getItem("bmAdminTheme");
  
      if (savedTheme === "dark" || savedTheme === "light") {
        return savedTheme;
      }
  
      return "light";
    });
  
    const [language, setLanguageState] = useState<LanguageCode>(() => {
      const savedLanguage = localStorage.getItem("bmAdminLanguage");
  
      if (
        savedLanguage === "en" ||
        savedLanguage === "vi" ||
        savedLanguage === "zh" ||
        savedLanguage === "ms"
      ) {
        return savedLanguage;
      }
  
      return "en";
    });
  
    const [textSize, setTextSizeState] = useState<TextSize>(() => {
      const savedTextSize = localStorage.getItem("bmAdminTextSize");
  
      if (
        savedTextSize === "small" ||
        savedTextSize === "medium" ||
        savedTextSize === "large"
      ) {
        return savedTextSize;
      }
  
      return "medium";
    });
  
    useEffect(() => {
      document.documentElement.setAttribute("data-theme", theme);
      localStorage.setItem("bmAdminTheme", theme);
    }, [theme]);
  
    useEffect(() => {
      document.documentElement.setAttribute("data-language", language);
      document.documentElement.lang =
        language === "vi"
          ? "vi"
          : language === "zh"
          ? "zh-CN"
          : language === "ms"
          ? "ms"
          : "en";
  
      localStorage.setItem("bmAdminLanguage", language);
    }, [language]);
  
    useEffect(() => {
      document.documentElement.setAttribute("data-text-size", textSize);
      localStorage.setItem("bmAdminTextSize", textSize);
    }, [textSize]);
  
    const value = useMemo<AppPreferencesContextValue>(() => {
      return {
        theme,
        language,
        textSize,
        setTheme: setThemeState,
        toggleTheme: () => {
          setThemeState((currentTheme) =>
            currentTheme === "light" ? "dark" : "light"
          );
        },
        setLanguage: setLanguageState,
        setTextSize: setTextSizeState,
        t: (key: string) => {
          return translations[language][key] || translations.en[key] || key;
        },
      };
    }, [theme, language, textSize]);
  
    return (
      <AppPreferencesContext.Provider value={value}>
        {children}
      </AppPreferencesContext.Provider>
    );
  }
  
  export function useAppPreferences() {
    const context = useContext(AppPreferencesContext);
  
    if (!context) {
      throw new Error(
        "useAppPreferences must be used inside AppPreferencesProvider"
      );
    }
  
    return context;
  }